[workspace]
resolver="2"
members=[
    "xml",
    "json"
]
[workspace.package]
version = "0.1.0"




[package]
name = "rust-mod"
version = "0.1.0"
edition = "2021"

[dependencies]
json={path = "./json",version = "0.1.0"}